<?php
require __DIR__ . '/includes/site.php';
require __DIR__ . '/includes/accreditation.php';
$documents = accreditation_documents();
render_header('Accreditation & Authorization | Medcon Edu', 'Review Medcon Edu’s Nigerian corporate registration and institutional authorizations for supporting students applying to medical schools in the Philippines.', '');
render_breadcrumb('Accreditation & Authorization');
?>
<section class="accreditation-hero section"><div class="container accreditation-hero-grid"><div><span class="eyebrow">Accreditation &amp; Authorization</span><h1>Your Journey Is Backed by Verified Institutions</h1><p>Medcon Edu is a registered Nigerian education consultancy working with recognized medical institutions to support students pursuing medical education in the Philippines. Review the registrations and authorizations behind our work.</p><div class="hero-actions"><a class="btn btn-primary" href="<?= e(site_url('apply.php')) ?>">Start Your Application</a><a class="btn btn-secondary" href="<?= e($whatsappUrl) ?>" target="_blank" rel="noopener">Speak to an Adviser</a></div></div><figure><img src="<?= e(site_url('img/woman-trust.png')) ?>" alt="Medcon Edu education adviser representing professional and trusted student support"><figcaption><span>CAC Registered</span><span>Institutionally Authorized</span><span>Nigeria-Based Student Support</span></figcaption></figure></div></section>
<section class="section soft accreditation-intro"><div class="container"><div class="section-heading"><span class="eyebrow">The verification journey</span><h2>A Verified Path from Nigeria to the Philippines</h2><p>Choosing an international education representative requires trust. Our verification journey begins with corporate registration in Nigeria and continues through formal authorization to support prospective medical students.</p></div><ol class="verification-summary"><li><span>01</span>Registered</li><li><span>02</span>Authorized</li><li><span>03</span>Student Support</li></ol></div></section>
<section class="section"><div class="container verification-timeline">
<?php foreach ($documents as $key => $document): ?><article class="verification-stage"><div class="verification-marker"><span><?= e($document['stage']) ?></span></div><div class="verification-copy"><div class="verification-meta"><span class="verification-status"><?= e($document['status']) ?></span><span>PDF document</span></div><span class="eyebrow"><?= e($document['label']) ?></span><h2><?= e($document['title']) ?></h2><p class="document-issuer">Issued by: <strong><?= e($document['issuer']) ?></strong></p><?php if ($document['facts']): ?><dl class="verification-facts"><?php foreach ($document['facts'] as $label => $value): ?><div><dt><?= e($label) ?></dt><dd><?= e($value) ?></dd></div><?php endforeach; ?></dl><?php endif; ?><?php if (!empty($document['scope'])): ?><ul class="check-list compact"><?php foreach ($document['scope'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul><?php endif; ?><p><?= e($document['explanation']) ?></p></div><div class="verification-document"><?php render_certificate_preview($key, $document); ?></div></article><?php endforeach; ?>
</div></section>
<section class="section soft"><div class="container split accreditation-meaning"><div><span class="eyebrow">Defined support</span><h2>What Our Authorizations Allow Us to Do</h2><p>Our support remains within the scope stated by each institution.</p></div><div><ul class="check-list"><li>Provide accurate programme information</li><li>Counsel prospective students and parents</li><li>Assist with application-document preparation</li><li>Coordinate admission-related communication</li><li>Support enrolment and pre-departure preparation</li><li>Provide administrative guidance for visa documentation</li></ul><p class="authorization-notice"><strong>Important:</strong> Final admission decisions remain with the respective educational institution. Visa approval remains solely with the relevant embassy, consulate, immigration authority or other competent government authority.</p></div></div></section>
<section class="section"><div class="container intro-grid"><div><span class="eyebrow">Trust and transparency</span><h2>Transparency Before Commitment</h2></div><div><p>We want students and parents to understand who they are working with before beginning an application. That is why our corporate registration and institutional authorizations are available for review.</p><ul class="document-link-list"><?php foreach ($documents as $key => $document): ?><li><a href="#stage-<?= e($document['stage']) ?>"><?= e($document['title']) ?></a></li><?php endforeach; ?></ul></div></div></section>
<section class="section cta-band"><div class="container cta-inner"><div><span class="eyebrow">Verified support</span><h2>Take the Next Step With a Verified Support Team</h2><p>Tell us where you are in your medical education journey, and a Medcon Edu adviser will explain your eligibility, application requirements and next steps.</p><a class="school-text-link accreditation-tertiary" href="<?= e(site_url('colleges.php')) ?>">Explore Our Partner Schools</a></div><div class="cta-actions"><a class="btn btn-primary" href="<?= e(site_url('apply.php')) ?>">Start Your Application</a><a class="btn btn-secondary" href="<?= e($whatsappUrl) ?>" target="_blank" rel="noopener">Chat on WhatsApp</a></div></div></section>
<?php render_certificate_dialog(); ?><script defer src="<?= e(site_url('scripts/accreditation.js')) ?>"></script><?php render_footer(); ?>
