<?php
require __DIR__ . '/includes/site.php';
render_header('PLTCI and The Manila Times College School of Medicine | Medcon', 'Compare the two verified Medcon partner medical colleges in the Philippines and request admission support.', 'colleges.php');
render_breadcrumb('Partner Colleges');
?>
<section class="fee-hero" id="fee-configurator" data-fee-configurator style="--fee-hero-image:url('<?= e(site_url('img/colleges.png')) ?>')">
<div class="container fee-hero-grid"><div class="fee-hero-copy"><span class="fee-hero-badge">Partner colleges · 2026 fee planner</span><h1>Know what it takes to start your medical journey.</h1><p>See the funds you need to leave Nigeria and begin school in the Philippines—not just the long-term total. Then compare your entry route and complete programme costs.</p><ul><li>See your estimated get-started amount first</li><li>Biology graduates can skip Pre-Med</li><li>Share the plan with parents or counsellors</li></ul><div class="fee-update"><span>Planning rates</span><strong>Updated 2 August 2026</strong></div></div>
<div class="fee-hero-calculator"><div class="fee-configurator"><form class="fee-config-form" data-fee-form><div class="fee-form-heading"><span>01</span><div><h3>Build your estimate</h3><p>Your choices update the breakdown instantly.</p></div></div>
<fieldset><legend>Academic background</legend><label class="fee-option"><input type="radio" name="background" value="secondary" checked><span><strong>Secondary school</strong><small>Pre-Med foundation included</small></span></label><label class="fee-option"><input type="radio" name="background" value="other-bachelor"><span><strong>Bachelor’s degree</strong><small>Non-biology background; Pre-Med included</small></span></label><label class="fee-option"><input type="radio" name="background" value="biology-bachelor"><span><strong>Bachelor’s in Biology</strong><small>Qualifying applicants skip Pre-Med</small></span></label></fieldset>
<label class="fee-select-label"><span>Preferred college</span><select name="college"><option value="tmtcs">The Manila Times College (TMTCS)</option><option value="pltci">PLTCI College of Medicine</option></select></label>
<fieldset><legend>Medcon support package</legend><label class="fee-option fee-package"><input type="radio" name="package" value="basic" checked><span><strong>Basic <b>$300</b></strong><small>Application processing and standard guidance</small></span></label><label class="fee-option fee-package"><input type="radio" name="package" value="premium"><span><strong>Premium <b>$500</b></strong><small>Enhanced help with visa, application, PCR and ancillary steps</small></span></label></fieldset>
<div class="fee-rule-note" data-premed-note><span aria-hidden="true">i</span><p>Pre-Med is included for this academic background.</p></div></form>
<div class="fee-results" aria-live="polite"><div class="fee-start-card"><div><span>To Travel Now, You Need</span><h3 data-start-usd>$0</h3><p data-start-ngn>₦0 at ₦1,390 / US$1</p></div><small>Initial academic stage, four months of accommodation and living costs, registration, selected Medcon support, and a US$2,000 travel/visa allowance. Remaining living costs can be handled month to month after arrival.</small></div>
<div class="fee-result-hero"><div><span>To Complete the Program You Need</span><h3 data-total-usd>$0</h3><p data-total-ngn>₦0 at ₦1,390 / US$1</p></div><span class="fee-duration" data-duration>—</span></div>
<div class="fee-result-summary"><div><span>College</span><strong data-college-name>—</strong></div><div><span>Entry route</span><strong data-entry-route>—</strong></div><div><span>Medcon package</span><strong data-package-name>—</strong></div></div>
<div class="fee-disclaimer"><strong>Planning estimate only.</strong><span>Actual invoices may change with exchange rates, school assessment, accommodation choice, airfare, visa charges and other third-party costs. Books, uniforms, excess electricity and personal expenses are not included.</span></div><div class="fee-actions"><a class="btn btn-primary" href="apply.php">Start your application</a><a class="btn btn-secondary" href="contact.php">Discuss this estimate</a></div></div>
<aside class="fee-yearly-column"><div><span>Payment schedule</span><h3>Full Breakdown</h3><p>Estimated payment by academic stage for family or sponsor planning.</p></div><div class="table-wrap"><table><thead><tr><th>Stage</th><th>Tuition</th><th>Living & accommodation</th><th>Total</th></tr></thead><tbody data-year-rows></tbody></table></div><div class="fee-share-actions"><button type="button" data-share-estimate>Share estimate</button><button type="button" data-download-estimate>Download PDF</button></div></aside>
</div></div></div></section>
<section class="section featured-colleges"><div class="container"><div class="featured-heading"><span class="partner-pill">Our partner institutions</span><h2>Partner Medical Colleges</h2><p>Admission, visa, travel and student settlement support provided by Medcon Educational Services and Consultancy Limited.</p></div><div class="featured-college-grid"><?php foreach ($collegeData as $college) { render_college_card($college); } ?></div></div></section>
<section class="section soft"><div class="container"><div class="section-heading"><span class="eyebrow">Compare colleges</span><h2>Quick planning comparison</h2></div><div class="table-wrap"><table class="info-table"><thead><tr><th>College</th><th>Location</th><th>Tuition / yr</th><th>Duration</th><th>Intakes</th></tr></thead><tbody><?php foreach ($collegeData as $college): ?><tr><td><?= e($college['name']) ?></td><td><?= e($college['location']) ?></td><td><?= e($college['tuition']) ?></td><td><?= e($college['duration']) ?></td><td><?= e($college['intakes']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></section>
<?php render_footer(); ?>
