<?php
require_once __DIR__ . '/../includes/student.php';
require_once __DIR__ . '/../includes/admin-layout.php';
require_role(['admin','super_admin']);
$user = current_user();
function admin_lead_value(array $lead, string $key, string $fallback = '—'): string { $value=trim((string)($lead[$key]??'')); return $value!==''?$value:$fallback; }
function admin_lead_result_label(string $result): string { return ['eligible'=>'Likely eligible','potential'=>'Further assessment','not-eligible'=>'Not eligible for direct entry'][$result]??ucwords(str_replace('-',' ',$result)); }
$leads=[];$csvError='';$csvPath=dirname(__DIR__,2).'/data/eligibility-submissions.csv';$handle=@fopen($csvPath,'rb');
if($handle){if(flock($handle,LOCK_SH)){$headers=fgetcsv($handle)?:[];while(($row=fgetcsv($handle))!==false){if(count($row)===count($headers))$leads[]=array_combine($headers,$row);}flock($handle,LOCK_UN);}fclose($handle);$leads=array_reverse($leads);}else{$csvError='The eligibility leads file could not be opened.';}
$query=trim((string)($_GET['q']??''));$resultFilter=trim((string)($_GET['result']??''));$filteredLeads=$leads;
if($query!==''){$needle=strtolower($query);$filteredLeads=array_values(array_filter($filteredLeads,function(array $lead)use($needle):bool{$searchable=implode(' ',[admin_lead_value($lead,'full_name',''),admin_lead_value($lead,'email',''),admin_lead_value($lead,'phone',''),admin_lead_value($lead,'current_country',''),admin_lead_value($lead,'nationality',''),admin_lead_value($lead,'education_level',''),admin_lead_value($lead,'degree_program','')]);return strpos(strtolower($searchable),$needle)!==false;}));}
if(in_array($resultFilter,['eligible','potential','not-eligible'],true))$filteredLeads=array_values(array_filter($filteredLeads,fn(array $lead):bool=>($lead['result']??'')===$resultFilter));
$counts=['eligible'=>0,'potential'=>0,'not-eligible'=>0];foreach($leads as $lead)if(isset($counts[$lead['result']??'']))$counts[$lead['result']]++;
$detailLabels=['current_country'=>'Current country','nationality'=>'Nationality','age_range'=>'Age range','education_level'=>'Highest education','secondary_credits'=>'Five secondary credits','mathematics'=>'Mathematics','english_language'=>'English Language','biology'=>'Biology','chemistry'=>'Chemistry','physics'=>'Physics','secondary_completion_year'=>'Secondary completion year','university_status'=>'University status','degree_program'=>'Degree programme','english_instruction'=>'Education in English','legal_case'=>'Legal or criminal case','medically_fit'=>'Medically fit','passport_status'=>'Passport','financial_sponsor'=>'Financial sponsor','cost_considered'=>'Cost readiness','contact_method'=>'Preferred contact','consultant_request'=>'Requested consultant'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-FZ8QPG3B9T"></script><script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-FZ8QPG3B9T');</script><title>Eligibility leads | Medcon Admin</title><link rel="stylesheet" href="<?= esc(site_url('assets/css/admin-leads.css')) ?>"><link rel="stylesheet" href="<?= esc(app_url('assets/css/app.css')) ?>"></head>
<body class="medcon-app mc-role-body"><?php admin_portal_header($user, 'leads'); ?>
<main class="mc-role-main admin-main"><section class="admin-title-row"><div><span class="mc-kicker">Admissions screening</span><h1>Eligibility leads</h1><p>Read-only submissions from the public eligibility checker.</p></div><div class="lead-total"><strong><?= count($leads) ?></strong><span>Total leads</span></div></section>
<section class="metric-grid" aria-label="Lead summary"><article><span>Likely eligible</span><strong><?= $counts['eligible'] ?></strong></article><article><span>Further assessment</span><strong><?= $counts['potential'] ?></strong></article><article><span>Not eligible for direct entry</span><strong><?= $counts['not-eligible'] ?></strong></article></section>
<section class="lead-panel"><form class="lead-filters" method="get"><label><span>Search leads</span><input type="search" name="q" value="<?= esc($query) ?>" placeholder="Name, email, phone, country, or programme"></label><label><span>Assessment</span><select name="result"><option value="">All results</option><option value="eligible"<?= $resultFilter==='eligible'?' selected':'' ?>>Likely eligible</option><option value="potential"<?= $resultFilter==='potential'?' selected':'' ?>>Further assessment</option><option value="not-eligible"<?= $resultFilter==='not-eligible'?' selected':'' ?>>Not eligible</option></select></label><button type="submit">Filter</button><?php if($query!==''||$resultFilter!==''): ?><a href="<?= esc(app_url('admin/leads.php')) ?>">Clear</a><?php endif; ?></form>
<?php if($csvError): ?><div class="admin-alert" role="alert"><?= esc($csvError) ?></div><?php elseif(!$filteredLeads): ?><div class="empty-state"><h2>No leads found</h2><p>Completed eligibility submissions will appear here.</p></div><?php else: ?><div class="lead-list"><?php foreach($filteredLeads as $index=>$lead): $resultKey=admin_lead_value($lead,'result','unknown');$phoneDigits=preg_replace('/[^0-9]/','',admin_lead_value($lead,'phone','')); ?><details class="lead-card"<?= $index===0?' open':'' ?>><summary><span class="lead-primary"><strong><?= esc(admin_lead_value($lead,'full_name')) ?></strong><small><?= esc(admin_lead_value($lead,'email')) ?> · <?= esc(admin_lead_value($lead,'phone')) ?></small></span><span class="lead-location"><?= esc(admin_lead_value($lead,'current_country')) ?></span><span class="result-badge result-<?= esc($resultKey) ?>"><?= esc(admin_lead_result_label($resultKey)) ?></span><time><?= esc(admin_lead_value($lead,'submitted_at')) ?></time></summary><div class="lead-detail"><div class="lead-actions"><a href="mailto:<?= esc(admin_lead_value($lead,'email','')) ?>">Email lead</a><?php if($phoneDigits): ?><a href="https://wa.me/<?= esc($phoneDigits) ?>" target="_blank" rel="noopener">Open WhatsApp</a><a href="tel:+<?= esc($phoneDigits) ?>">Call lead</a><?php endif; ?></div><dl class="detail-grid"><?php foreach($detailLabels as $key=>$label): ?><div><dt><?= esc($label) ?></dt><dd><?= esc(admin_lead_value($lead,$key)) ?></dd></div><?php endforeach; ?></dl></div></details><?php endforeach; ?></div><?php endif; ?></section></main><?php admin_portal_footer(); ?></body></html>
