<?php
require __DIR__ . '/includes/site.php';
require_once __DIR__ . '/app/includes/db.php';
require_once __DIR__ . '/app/includes/functions.php';
$agentErrors=[]; $agentSubmitted=false;
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['agent_registration'])) {
    $fullName=trim($_POST['name']??''); $email=strtolower(trim($_POST['email']??'')); $phone=trim($_POST['phone']??''); $country=trim($_POST['country']??''); $city=trim($_POST['city']??''); $organization=trim($_POST['organization']??''); $experience=trim($_POST['experience']??''); $volume=trim($_POST['volume']??''); $website=trim($_POST['website']??''); $password=$_POST['password']??''; $confirm=$_POST['confirm_password']??''; $slug=strtolower(trim($_POST['referral_slug']??''));
    $nameParts=preg_split('/\s+/', $fullName, 2); $firstName=$nameParts[0]??''; $lastName=$nameParts[1]??'';
    if (!verify_csrf($_POST['_csrf']??'')) $agentErrors[]='Invalid form submission.';
    if ($firstName==='' || $lastName==='' || $email==='' || $phone==='' || $country==='' || $password==='' || $confirm==='') $agentErrors[]='Complete all required fields.';
    if (!filter_var($email,FILTER_VALIDATE_EMAIL)) $agentErrors[]='Enter a valid email address.';
    if (strlen($password)<8) $agentErrors[]='Password must be at least 8 characters.';
    if ($password!==$confirm) $agentErrors[]='Passwords do not match.';
    if (!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$slug)) $agentErrors[]='Use lowercase letters, numbers, and single hyphens for your referral link name.';
    if (!$agentErrors) {
        $check=$pdo->prepare('SELECT id FROM users WHERE email=? LIMIT 1'); $check->execute([$email]); if ($check->fetch()) $agentErrors[]='An account with that email already exists.';
        $check=$pdo->prepare('SELECT id FROM agents WHERE referral_slug=? LIMIT 1'); $check->execute([$slug]); if ($check->fetch()) $agentErrors[]='That referral link name is already in use.';
    }
    if (!$agentErrors) {
        try { $pdo->beginTransaction(); $now=date('Y-m-d H:i:s'); $insert=$pdo->prepare("INSERT INTO users (role,first_name,last_name,email,phone,country,password_hash,status,email_verified,created_at,updated_at) VALUES ('agent',?,?,?,?,?,?, 'active',0,?,?)"); $insert->execute([$firstName,$lastName,$email,$phone,$country,password_hash($password,PASSWORD_DEFAULT),$now,$now]); $userId=(int)$pdo->lastInsertId(); $agentInsert=$pdo->prepare('INSERT INTO agents (user_id,organization_name,city,recruitment_experience,expected_student_volume,website_social_link,referral_code,referral_slug) VALUES (?,?,?,?,?,?,?,?)'); $agentInsert->execute([$userId,$organization,$city,$experience,$volume,$website,'pending-'.$userId,$slug]); $agentId=(int)$pdo->lastInsertId(); $pdo->prepare('UPDATE agents SET referral_code=? WHERE id=?')->execute(['Medcon'.str_pad((string)$agentId,3,'0',STR_PAD_LEFT),$agentId]); $pdo->commit(); $agentSubmitted=true; } catch (Throwable $exception) { if($pdo->inTransaction())$pdo->rollBack(); $agentErrors[]='Your application could not be saved. Please try again.'; }
    }
}
render_header('Become a Student Recruitment Agent | Medcon', 'Register interest in becoming a Medcon student recruitment agent or referral partner.', 'for-agents.php');
render_breadcrumb('For Agents');
render_page_hero('AGENT PARTNERSHIPS', 'Partner with Medcon as a student recruitment agent', 'Medcon works with education agents, school counsellors, student recruiters, and trusted community representatives who want to refer qualified students for international medical education opportunities.', ['label' => 'Apply to Become an Agent', 'href' => '#agent-form']);
$benefits = [
    ['title' => 'Partner College Information', 'body' => 'Receive clear information about available colleges, programmes, tuition ranges, and intake periods.'],
    ['title' => 'Student Referral Channel', 'body' => 'Refer qualified students through a structured enquiry process.'],
    ['title' => 'Admissions Support', 'body' => 'Work with a team that supports students and families through next-step guidance.'],
    ['title' => 'Marketing Support', 'body' => 'Access approved messaging, college information, and promotional direction where available.'],
    ['title' => 'Commission Opportunity', 'body' => 'Earn approved commissions based on Medcon agent policy and confirmed student outcomes.'],
    ['title' => 'Dedicated Communication', 'body' => 'Get a clearer channel for follow-up and student enquiry support.'],
];
$steps = ['Submit the agent application form', 'Medcon reviews your information', 'Approved agents receive partnership guidance', 'You refer qualified student leads', 'Medcon supports the admissions enquiry process', 'Approved commissions are handled based on policy'];
?>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">Who this is for</span><h2>Agent and referral partner profiles</h2></div><ul class="check-list columns"><li>Education consultants</li><li>School counsellors</li><li>Student recruiters</li><li>Community representatives</li><li>Study abroad agents</li><li>Individuals with student networks</li></ul></div></section>
<section class="section soft"><div class="container"><div class="section-heading"><span class="eyebrow">Agent benefits</span><h2>Why partner with Medcon?</h2></div><?php render_cards($benefits); ?></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">How it works</span><h2>How agent partnership works</h2></div><?php render_steps($steps); ?></div></section>
<section class="section soft" id="agent-form"><div class="container split"><div><span class="eyebrow">Agent registration</span><h2>Apply to become an agent</h2><p>Complete the form and Medcon will review your information before confirming next steps.</p></div><form class="form-card" method="post"><input type="hidden" name="agent_registration" value="1"><?= csrf_field() ?><h3>Agent application form</h3><?php if($agentErrors): ?><div class="form-status" role="alert"><?php foreach($agentErrors as $error): ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php elseif($agentSubmitted): ?><div class="form-status" role="status">Application received. Medcon will review your account and contact you with next steps.</div><?php endif; ?><p class="form-note"><span class="required-marker" aria-hidden="true">*</span> indicates a required field.</p><div class="form-grid"><label><?php form_label('Full name', true); ?><input required type="text" name="name" autocomplete="name" value="<?= esc($_POST['name']??'') ?>"></label><label><?php form_label('Email address', true); ?><input required type="email" name="email" autocomplete="email" value="<?= esc($_POST['email']??'') ?>"></label><label><?php form_label('Phone number', true); ?><input required type="tel" name="phone" autocomplete="tel" value="<?= esc($_POST['phone']??'') ?>"></label><label><?php form_label('Country', true); ?><input required type="text" name="country" autocomplete="country-name" value="<?= esc($_POST['country']??'') ?>"></label><label><?php form_label('City or state'); ?><input type="text" name="city" value="<?= esc($_POST['city']??'') ?>"></label><label><?php form_label('Organization name'); ?><input type="text" name="organization" value="<?= esc($_POST['organization']??'') ?>"></label><label><?php form_label('Referral link name', true); ?><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" name="referral_slug" placeholder="e.g. horizon-education" value="<?= esc($_POST['referral_slug']??'') ?>"></label><label><?php form_label('Recruitment experience'); ?><input type="text" name="experience" value="<?= esc($_POST['experience']??'') ?>"></label><label><?php form_label('Expected student volume'); ?><input type="text" name="volume" value="<?= esc($_POST['volume']??'') ?>"></label><label><?php form_label('Website or social link'); ?><input type="url" name="website" value="<?= esc($_POST['website']??'') ?>"></label><label><?php form_label('Password', true); ?><input required type="password" name="password" autocomplete="new-password"></label><label><?php form_label('Confirm password', true); ?><input required type="password" name="confirm_password" autocomplete="new-password"></label></div><label><?php form_label('Additional information'); ?><textarea name="message" rows="4"><?= esc($_POST['message']??'') ?></textarea></label><button class="btn btn-primary" type="submit">Apply to Become an Agent</button></form></div></section>
<?php render_footer(); ?>
