<?php
require_once __DIR__ . '/../includes/auth.php';
require_once dirname(__DIR__,2) . '/scripts/mail/AccountNotifications.php';
register_shutdown_function('crafted_by_aqqute');
$agent=require_approved_agent($pdo); $errors=[]; $created=null;
if ($_SERVER['REQUEST_METHOD']==='POST') {
    $first=trim($_POST['first_name']??''); $last=trim($_POST['last_name']??''); $email=strtolower(trim($_POST['email']??'')); $phone=trim($_POST['phone']??''); $country=trim($_POST['country']??''); $password=$_POST['password']??'';
    if (!verify_csrf($_POST['_csrf']??'')) $errors[]='Your session expired. Refresh the page and try again.';
    if ($first===''||$last===''||$email===''||$password==='') $errors[]='Complete all required fields.';
    if (!filter_var($email,FILTER_VALIDATE_EMAIL)) $errors[]='Enter a valid email address.';
    if (strlen($password)<8) $errors[]='The temporary password must be at least 8 characters.';
    if (!$errors) { $check=$pdo->prepare('SELECT id FROM users WHERE email=? LIMIT 1'); $check->execute([$email]); if($check->fetch())$errors[]='A user with that email already exists.'; }
    if (!$errors) { try { $pdo->beginTransaction(); $now=date('Y-m-d H:i:s'); $insert=$pdo->prepare("INSERT INTO users (role,first_name,last_name,email,phone,country,password_hash,status,email_verified,created_at,updated_at) VALUES ('student',?,?,?,?,?,?, 'active',0,?,?)"); $insert->execute([$first,$last,$email,$phone,$country,password_hash($password,PASSWORD_DEFAULT),$now,$now]); $userId=(int)$pdo->lastInsertId(); $studentInsert=$pdo->prepare('INSERT INTO students (user_id,agent_id,referral_code,heard_about,created_at,updated_at) VALUES (?,?,?,?,?,?)'); $studentInsert->execute([$userId,$agent['id'],$agent['referral_code'],'Agent',$now,$now]);$studentId=(int)$pdo->lastInsertId();$pdo->commit();medcon_send_verification($pdo,$userId);medcon_notify_affiliate($pdo,(int)$agent['id'],$studentId);$created=['name'=>$first.' '.$last,'email'=>$email,'password'=>$password]; } catch(Throwable $exception) { if($pdo->inTransaction())$pdo->rollBack(); $errors[]='The student could not be registered.'; } }
}
?>
<!doctype html><html lang="en"><head><?php require_once dirname(__DIR__, 2) . '/includes/analytics.php'; ?><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Register student | Medcon Agent</title><link rel="stylesheet" href="<?= esc(app_url('assets/css/app.css')) ?>"></head><body class="medcon-app mc-role-body"><header class="mc-role-topbar"><a href="<?= esc(app_url('agent/dashboard.php')) ?>" class="mc-portal-logo"><img src="<?= esc(site_url('img/logo.svg')) ?>" alt="Medcon"><span>Agent portal</span></a><div class="mc-portal-user"><span><?= esc($agent['first_name'].' '.$agent['last_name']) ?></span><a href="<?= esc(app_url('logout.php')) ?>">Sign out</a></div></header><main class="mc-role-main"><div class="mc-portal-heading"><div><span class="mc-kicker">Student referral</span><h1>Register a student</h1><p>The student can sign in immediately with the credentials you provide.</p></div><a class="mc-arrow-link" href="<?= esc(app_url('agent/dashboard.php')) ?>">Back to dashboard</a></div><?php if($errors): ?><div class="mc-errors" role="alert"><?php foreach($errors as $error): ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?><?php if($created): ?><section class="mc-panel"><h2>Student account created</h2><p>Share these sign-in details securely with <?= esc($created['name']) ?>.</p><dl class="mc-detail-list"><div><dt>Email</dt><dd><?= esc($created['email']) ?></dd></div><div><dt>Temporary password</dt><dd><?= esc($created['password']) ?></dd></div></dl><a class="mc-btn-primary" href="<?= esc(app_url('agent/dashboard.php')) ?>">View dashboard</a></section><?php else: ?><form method="post" class="mc-panel mc-auth-form"><?= csrf_field() ?><div class="mc-field-grid"><label><span>First name *</span><input name="first_name" required value="<?= esc($_POST['first_name']??'') ?>"></label><label><span>Last name *</span><input name="last_name" required value="<?= esc($_POST['last_name']??'') ?>"></label><label><span>Email *</span><input type="email" name="email" required value="<?= esc($_POST['email']??'') ?>"></label><label><span>Phone</span><input name="phone" value="<?= esc($_POST['phone']??'') ?>"></label><label><span>Country</span><input name="country" value="<?= esc($_POST['country']??'') ?>"></label><label><span>Temporary password *</span><div class="mc-password-wrapper"><input type="password" name="password" required minlength="8"><button type="button" class="mc-password-toggle" aria-label="Show password" data-show="false">👁</button></div></label></div><button class="mc-btn-primary" type="submit">Create student account</button></form><?php endif; ?></main></body></html>
