<?php
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/functions.php';require_once __DIR__.'/includes/auth-layout.php';
$token=trim((string)($_GET['token']??$_POST['token']??''));$tokenHash=$token!==''?hash('sha256',$token):'';$errors=[];$complete=false;
$load=function()use($pdo,$tokenHash){$q=$pdo->prepare('SELECT t.id token_id,t.assessment_id,a.* FROM eligibility_account_tokens t JOIN eligibility_assessments a ON a.id=t.assessment_id WHERE t.token_hash=? AND t.used_at IS NULL AND t.expires_at>NOW() LIMIT 1');$q->execute([$tokenHash]);return $q->fetch()?:null;};$assessment=$tokenHash!==''?$load():null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf($_POST['_csrf']??''))$errors[]='Your session expired. Refresh and try again.';$password=(string)($_POST['password']??'');$confirm=(string)($_POST['confirm_password']??'');if(strlen($password)<8)$errors[]='Password must be at least 8 characters.';if($password!==$confirm)$errors[]='Passwords do not match.';if(!$assessment)$errors[]='This account link is invalid, expired, or has already been used.';
 if(!$errors){$pdo->beginTransaction();try{$lock=$pdo->prepare('SELECT t.id token_id,t.assessment_id,a.* FROM eligibility_account_tokens t JOIN eligibility_assessments a ON a.id=t.assessment_id WHERE t.token_hash=? AND t.used_at IS NULL AND t.expires_at>NOW() LIMIT 1 FOR UPDATE');$lock->execute([$tokenHash]);$assessment=$lock->fetch();if(!$assessment)throw new RuntimeException('This account link is no longer available.');$existing=$pdo->prepare('SELECT id FROM users WHERE email=? LIMIT 1');$existing->execute([$assessment['email']]);if($existing->fetchColumn())throw new RuntimeException('An account already exists for this email. Sign in instead.');$answers=json_decode($assessment['answers_json'],true,512,JSON_THROW_ON_ERROR);$parts=preg_split('/\s+/',trim($assessment['full_name']),2);$first=$parts[0]?:'Student';$last=$parts[1]??'';$country=($answers['current_country']??'')==='Other'?($answers['current_country_other']??'Other'):($answers['current_country']??'');$nationality=($answers['nationality']??'')==='Other'?($answers['nationality_other']??'Other'):($answers['nationality']??'');$now=date('Y-m-d H:i:s');$pdo->prepare("INSERT INTO users(role,first_name,last_name,email,phone,country,password_hash,status,email_verified,created_at,updated_at) VALUES('student',?,?,?,?,?,?,'active',1,?,?)")->execute([$first,$last,$assessment['email'],$assessment['phone'],$country,password_hash($password,PASSWORD_DEFAULT),$now,$now]);$userId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO students(user_id,nationality,education_level,created_at,updated_at) VALUES(?,?,?,?,?)')->execute([$userId,$nationality,$answers['education_level']??null,$now,$now]);$studentId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE eligibility_assessments SET user_id=?,student_id=? WHERE email=?')->execute([$userId,$studentId,$assessment['email']]);$pdo->prepare('UPDATE eligibility_account_tokens SET used_at=NOW() WHERE assessment_id=? AND used_at IS NULL')->execute([$assessment['assessment_id']]);$pdo->commit();$_SESSION['user']=['id'=>$userId,'role'=>'student','full_name'=>trim($first.' '.$last),'email'=>$assessment['email']];header('Location: '.app_url('student/eligibility.php'));exit;}catch(Throwable $exception){if($pdo->inTransaction())$pdo->rollBack();$errors[]=$exception instanceof RuntimeException?$exception->getMessage():'Your account could not be created. Please try again.';}}
}
auth_page_start('Complete account','Your eligibility result is ready','Set one secure password to continue.','Your email was verified through the private link sent with your result.','mc-signup-page');?>
<div class="mc-auth-top"><span>Already created an account?</span><a class="mc-text-button" href="login.php">Sign in</a></div><div class="mc-form-heading"><span class="mc-kicker">Verified eligibility account</span><h1>Choose your password</h1><p><?php if($assessment):?>Welcome, <?=esc($assessment['full_name'])?>. Your assessment details will already be available in your dashboard.<?php else:?>This account link is invalid, expired, or has already been used.<?php endif;?></p></div><?php if($errors):?><div class="mc-errors"><?php foreach(array_unique($errors) as $error):?><div><?=esc($error)?></div><?php endforeach;?></div><?php endif;?><?php if($assessment):?><form method="post" class="mc-auth-form"><?=csrf_field()?><input type="hidden" name="token" value="<?=esc($token)?>"><label><span>Password</span><div class="mc-password-wrapper"><input type="password" name="password" minlength="8" autocomplete="new-password" required><button type="button" class="mc-password-toggle" aria-label="Show password" data-show="false">👁</button></div></label><label><span>Confirm password</span><div class="mc-password-wrapper"><input type="password" name="confirm_password" minlength="8" autocomplete="new-password" required><button type="button" class="mc-password-toggle" aria-label="Show password" data-show="false">👁</button></div></label><button class="mc-btn-primary">Create account and open dashboard</button></form><?php else:?><a class="mc-btn-primary mc-button-link" href="login.php">Go to sign in</a><?php endif;auth_page_end();
