<?php
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/functions.php';require_once __DIR__.'/includes/auth-layout.php';require_once dirname(__DIR__).'/scripts/mail/TokenService.php';require_once dirname(__DIR__).'/scripts/mail/NotificationService.php';require_once dirname(__DIR__).'/scripts/mail/config.php';
$submitted=false;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf($_POST['_csrf']??''))$error='Invalid form submission.';
 elseif(!filter_var(trim($_POST['email']??''),FILTER_VALIDATE_EMAIL))$error='Enter a valid email address.';
 else{$submitted=true;$email=strtolower(trim($_POST['email']));$query=$pdo->prepare("SELECT id FROM users WHERE email=? AND status='active' LIMIT 1");$query->execute([$email]);$userId=(int)$query->fetchColumn();if($userId){$rate=$pdo->prepare('SELECT COUNT(*) FROM password_resets WHERE user_id=? AND created_at>DATE_SUB(NOW(),INTERVAL 15 MINUTE)');$rate->execute([$userId]);if((int)$rate->fetchColumn()<3){try{$reset=(new MedconTokenService($pdo))->createReset($userId);$config=medcon_mail_config();medcon_notify($pdo,'password.reset_requested',$userId,'password.reset_requested:reset:'.$reset['id'],['action_url'=>$config['base_url'].'/app/reset-password.php?token='.rawurlencode($reset['token'])],'password_reset',$reset['id']);}catch(Throwable $e){error_log('Medcon reset request failed.');}}}}
}
auth_page_start('Forgot password','Secure account recovery','Return to your application with confidence.','Use the email connected to your Medcon profile to begin account recovery.','mc-forgot-page');?>
<div class="mc-auth-top"><span>Remembered your password?</span><a class="mc-text-button" href="login.php">Sign in</a></div>
<?php if($submitted):?><div class="mc-form-heading"><span class="mc-kicker">Check your inbox</span><h1>Recovery request received</h1><p>If an active account exists for that email, a secure reset link has been sent. It expires in one hour.</p></div><div class="mc-success">For privacy, this message is the same for every email address.</div><p class="mc-support-note"><a href="login.php">Return to sign in</a></p>
<?php else:?><div class="mc-form-heading"><span class="mc-kicker">Account recovery</span><h1>Reset your password</h1><p>Enter the email address connected to your account.</p></div><?php if($error):?><div class="mc-errors"><?=esc($error)?></div><?php endif;?><form method="post" class="mc-auth-form" novalidate><?=csrf_field()?><label><span>Email address</span><input type="email" name="email" autocomplete="email" required value="<?=esc($_POST['email']??'')?>"></label><button class="mc-btn-primary" type="submit">Send reset link</button></form><?php endif;auth_page_end();
