<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__,2).'/app/includes/db.php';require_once __DIR__.'/TokenService.php';
$email='mail-test-'.bin2hex(random_bytes(5)).'@example.test';$userId=0;$failures=[];$assert=function(bool $ok,string $label)use(&$failures){echo($ok?'PASS ':'FAIL ').$label.PHP_EOL;if(!$ok)$failures[]=$label;};
try{
 $now=date('Y-m-d H:i:s');$pdo->prepare("INSERT INTO users(role,first_name,last_name,email,password_hash,status,email_verified,created_at,updated_at) VALUES('student','Mail','Test',?,?,'active',0,?,?)")->execute([$email,password_hash('Initial-pass-1',PASSWORD_DEFAULT),$now,$now]);$userId=(int)$pdo->lastInsertId();$tokens=new MedconTokenService($pdo);
 $expired=$tokens->createVerification($userId);$pdo->prepare('UPDATE email_verification_tokens SET expires_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?')->execute([$expired['id']]);$assert($tokens->consumeVerification($expired['token'])===null,'expired verification token is rejected');
 $verification=$tokens->createVerification($userId);$q=$pdo->prepare('SELECT token_hash FROM email_verification_tokens WHERE id=?');$q->execute([$verification['id']]);$stored=(string)$q->fetchColumn();$assert($stored===hash('sha256',$verification['token'])&&$stored!==$verification['token'],'verification token is stored only as a hash');$assert($tokens->consumeVerification($verification['token'])===$userId,'verification token works once');$assert($tokens->consumeVerification($verification['token'])===null,'verification token cannot be reused');
 $reset=$tokens->createReset($userId);$q=$pdo->prepare('SELECT token FROM password_resets WHERE id=?');$q->execute([$reset['id']]);$assert((string)$q->fetchColumn()===hash('sha256',$reset['token']),'reset token is stored only as a hash');$consumed=$tokens->consumeReset($reset['token'],password_hash('Changed-pass-2',PASSWORD_DEFAULT));$assert(($consumed['user_id']??0)===$userId,'reset token changes the password once');$assert($tokens->consumeReset($reset['token'],password_hash('Never-used-3',PASSWORD_DEFAULT))===null,'reset token cannot be reused');
 $key='test-idempotency-'.bin2hex(random_bytes(6));$insert=$pdo->prepare("INSERT INTO email_logs(event_key,recipient_user_id,recipient_email,idempotency_key,status)VALUES('test',?,?,?,'skipped')");$insert->execute([$userId,$email,$key]);$duplicateBlocked=false;try{$insert->execute([$userId,$email,$key]);}catch(PDOException $e){$duplicateBlocked=(string)$e->getCode()==='23000';}$assert($duplicateBlocked,'duplicate event idempotency key is blocked');$pdo->prepare('DELETE FROM email_logs WHERE idempotency_key=?')->execute([$key]);
}finally{if($userId){$pdo->prepare('DELETE FROM email_logs WHERE recipient_user_id=?')->execute([$userId]);$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$userId]);}}
exit($failures?1:0);
