<?php
require_once dirname(__DIR__).'/app/includes/db.php';require_once dirname(__DIR__).'/app/includes/functions.php';
require_once dirname(__DIR__).'/scripts/mail/NotificationService.php';require_once dirname(__DIR__).'/scripts/mail/config.php';

function inquiry_options():array{return ['person_type'=>['student'=>'Student','parent'=>'Parent','agent'=>'Agent'],'education_level'=>['Secondary School'=>'Secondary School','WAEC / NECO / SSCE'=>'WAEC / NECO / SSCE','A Levels / Foundation'=>'A Levels / Foundation',"Bachelor's degree"=>"Bachelor's degree",'Postgraduate degree'=>'Postgraduate degree','Other'=>'Other'],'intended_intake'=>['September 2026'=>'September 2026','September 2027'=>'September 2027'],'programme'=>['Not sure yet'=>'Not sure yet','Doctor of Medicine (MD)'=>'Doctor of Medicine (MD)','BS-MD Medical Programme'=>'BS-MD Medical Programme']];}
function inquiry_state():array{return $GLOBALS['medcon_inquiry_state']??['errors'=>[],'values'=>[],'success'=>($_GET['inquiry']??'')==='received'];}
function handle_inquiry_submission(string $source):void{
 global $pdo;$state=['errors'=>[],'values'=>[],'success'=>($_GET['inquiry']??'')==='received'];
 if($_SERVER['REQUEST_METHOD']!=='POST'||($_POST['form_name']??'')!=='public_inquiry'){$GLOBALS['medcon_inquiry_state']=$state;return;}
 $fields=['person_type','full_name','email','phone','country','education_level','preferred_programme','preferred_college','intended_intake','message'];foreach($fields as $field)$state['values'][$field]=trim((string)($_POST[$field]??''));$channel=($_POST['submit_action']??'form')==='whatsapp'?'whatsapp':'form';$options=inquiry_options();
 if(!verify_csrf($_POST['_csrf']??''))$state['errors'][]='Your session expired. Refresh the page and try again.';
 foreach(['person_type','full_name','email','phone','country','education_level','intended_intake'] as $required)if($state['values'][$required]===''){$state['errors'][]='Complete every required field.';break;}
 if(!filter_var($state['values']['email'],FILTER_VALIDATE_EMAIL))$state['errors'][]='Enter a valid email address.';
 if(!isset($options['person_type'][$state['values']['person_type']]))$state['errors'][]='Select whether you are a student, parent, or agent.';
 if(!isset($options['education_level'][$state['values']['education_level']]))$state['errors'][]='Select a valid education level.';
 if(!isset($options['intended_intake'][$state['values']['intended_intake']]))$state['errors'][]='Select a valid intended intake.';
 if(!isset($_POST['consent']))$state['errors'][]='Agree to be contacted about this enquiry.';
 if(!$state['errors']){
  $stmt=$pdo->prepare("INSERT INTO inquiries(source_page,person_type,full_name,email,phone,country,education_level,preferred_programme,preferred_college,intended_intake,message,submission_channel,status,consent_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'not_contacted',NOW())");$stmt->execute([$source,$state['values']['person_type'],$state['values']['full_name'],strtolower($state['values']['email']),$state['values']['phone'],$state['values']['country'],$state['values']['education_level'],$state['values']['preferred_programme']?:null,$state['values']['preferred_college']?:null,$state['values']['intended_intake'],$state['values']['message']?:null,$channel]);$inquiryId=(int)$pdo->lastInsertId();
  if($channel==='whatsapp'){$lines=['Hello Medcon, I have submitted an enquiry.','Name: '.$state['values']['full_name'],'I am a: '.$options['person_type'][$state['values']['person_type']],'Email: '.$state['values']['email'],'Phone: '.$state['values']['phone'],'Country: '.$state['values']['country'],'Education: '.$state['values']['education_level'],'Programme: '.($state['values']['preferred_programme']?:'Not specified'),'College: '.($state['values']['preferred_college']?:'Not specified'),'Intended intake: '.$state['values']['intended_intake'],'Message: '.($state['values']['message']?:'None')];header('Location: https://wa.me/2347036961056?text='.rawurlencode(implode("\n",$lines)));exit;}
  $mailConfig=medcon_mail_config();medcon_notify_email($pdo,'inquiry.received',$state['values']['email'],'inquiry.received:inquiry:'.$inquiryId,['name'=>$state['values']['full_name'],'action_url'=>$mailConfig['base_url'].'/app/signup.php','eligibility_url'=>$mailConfig['base_url'].'/eligibility-checker.php','fees_url'=>$mailConfig['base_url'].'/colleges.php#fee-configurator'],'inquiry',$inquiryId);
  $path=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';
  // Only a saved enquiry can authorize the thank-you conversion event.
  $_SESSION['inquiry_conversion']=['path'=>$path,'expires'=>time()+600];
  header('Location: '.$path.'?inquiry=received#inquiry-form');exit;
 }
 $GLOBALS['medcon_inquiry_state']=$state;
}
function render_inquiry_form(array $colleges=[],string $selectedCollege=''):void{$state=inquiry_state();$values=$state['values'];$options=inquiry_options();?>
<form class="form-card" method="post" id="inquiry-form"><?=csrf_field()?><input type="hidden" name="form_name" value="public_inquiry"><h3>Application enquiry form</h3><p class="form-note"><span class="required-marker" aria-hidden="true">*</span> indicates a required field.</p><?php if($state['errors']):?><div class="form-status" role="alert"><?php foreach($state['errors'] as $error):?><div><?=e($error)?></div><?php endforeach;?></div><?php elseif($state['success']):?><div class="form-status" role="status">Thank you. Your enquiry has been saved and Medcon will contact you.</div><?php endif;?><div class="form-grid">
<label><?php form_label('I am a',true);?><select required name="person_type"><option value="">Select one</option><?php foreach($options['person_type'] as $value=>$label):?><option value="<?=e($value)?>"<?=($values['person_type']??'')===$value?' selected':''?>><?=e($label)?></option><?php endforeach;?></select></label>
<label><?php form_label('Full name',true);?><input required name="full_name" autocomplete="name" value="<?=e($values['full_name']??'')?>"></label><label><?php form_label('Email address',true);?><input required type="email" name="email" autocomplete="email" value="<?=e($values['email']??'')?>"></label><label><?php form_label('Phone number',true);?><input required type="tel" name="phone" autocomplete="tel" value="<?=e($values['phone']??'')?>"></label><label><?php form_label('Country',true);?><input required name="country" autocomplete="country-name" value="<?=e($values['country']??'Nigeria')?>"></label>
<label><?php form_label('Current education level',true);?><select required name="education_level"><option value="">Select level</option><?php foreach($options['education_level'] as $value=>$label):?><option value="<?=e($value)?>"<?=($values['education_level']??'')===$value?' selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label><?php form_label('Preferred programme');?><select name="preferred_programme"><?php foreach($options['programme'] as $value=>$label):?><option value="<?=e($value)?>"<?=($values['preferred_programme']??'')===$value?' selected':''?>><?=e($label)?></option><?php endforeach;?></select></label>
<label><?php form_label('Preferred college');?><select name="preferred_college"><option value="">Not sure yet</option><?php foreach($colleges as $college):$value=(string)$college['name'];$chosen=(string)($values['preferred_college']??$selectedCollege);?><option value="<?=e($value)?>"<?=($chosen===$value||$chosen===($college['slug']??''))?' selected':''?>><?=e($college['name'])?></option><?php endforeach;?></select></label><label><?php form_label('Intended intake',true);?><select required name="intended_intake"><option value="">Select intake</option><?php foreach($options['intended_intake'] as $value=>$label):?><option value="<?=e($value)?>"<?=($values['intended_intake']??'')===$value?' selected':''?>><?=e($label)?></option><?php endforeach;?></select></label></div>
<label><?php form_label('Questions or message');?><textarea name="message" rows="4"><?=e($values['message']??'')?></textarea></label><label class="checkbox-line"><input required type="checkbox" name="consent" value="1"<?=isset($_POST['consent'])?' checked':''?>><span>I agree that Medcon may contact me about this enquiry. <span class="required-marker" aria-hidden="true">*</span></span></label><div class="hero-actions"><button class="btn btn-primary" name="submit_action" value="form" type="submit">Submit Enquiry</button><button class="btn btn-secondary inquiry-whatsapp" name="submit_action" value="whatsapp" type="submit">Continue on WhatsApp</button></div><p class="form-note">Continuing on WhatsApp saves this enquiry, then opens a message containing the information above.</p></form><?php }
