<?php

function school_catalogue(): array
{
    $commonAdmissions = [
        'process' => ['title' => 'Admission process', 'kicker' => 'Your route in', 'body' => 'Medcon supports applicants from initial eligibility review through document preparation, school submission, offer acceptance, visa guidance and pre-departure planning.', 'items' => ['Eligibility review and counselling', 'Submit academic and identity documents', 'Complete the school evaluation and interview', 'Receive and accept the admission decision', 'Complete visa and travel preparation']],
        'eligibility' => ['title' => 'Eligibility criteria', 'kicker' => 'Who can apply', 'body' => 'Applicants complete the required science education, present their academic record, demonstrate English readiness and pass the school’s formal admission evaluation.'],
        'jamb' => ['title' => 'JAMB criteria', 'kicker' => 'For Nigerian applicants', 'body' => 'JAMB replaces the Indian NEET reference for Nigerian applicants. Applicants need a score of 200 or above, representing performance above the 50th percentile, alongside the school’s academic and documentary requirements.'],
        'documents' => ['title' => 'Documents required', 'kicker' => 'Prepare early', 'items' => ['Passport data page', 'Birth certificate', 'Academic certificates and transcripts', 'Passport photographs', 'Certificate of good moral character', 'Medical examination certificate', 'Required entrance-test results']],
        'visa' => ['title' => 'Student visa', 'kicker' => 'Philippine 9(f) process', 'body' => 'The accepting school initiates the process in the Philippines. After local clearances and visa authority reach the Philippine Embassy in Abuja, the student attends a mandatory in-person interview for visa stamping.', 'items' => ['1. Secure admission and receive the official Notice of Acceptance from a school authorised to enrol international students.', '2. The school submits the student’s records to CHED; approved records proceed through the DFA in Manila.', '3. Wait for visa authority to reach the Philippine Embassy, 2 Kainji Street, corner Lake Chad, Maitama, Abuja, then book the interview.', '4. Attend the interview with original documents; after successful evaluation, the Embassy stamps the 9(f) visa.', 'Passport valid at least six months beyond the intended stay, completed FA Form No. 2 and two recent white-background photographs.', 'Original Notice of Acceptance plus MFA-authenticated WASSCE, diplomas or university transcripts.', 'MFA-authenticated Nigerian Police clearance and a medical certificate with laboratory results and chest X-ray.', 'Certified bank statements and notarised sponsor affidavit showing funds for tuition, accommodation and living expenses.']],
        'faqs' => ['title' => 'Admissions FAQs', 'kicker' => 'Common questions', 'faqs' => [['question' => 'Can international students apply?', 'answer' => 'Yes. International students apply with the listed academic, documentary and immigration requirements.'], ['question' => 'Does JAMB replace the Philippine entrance test?', 'answer' => 'JAMB replaces the Indian NEET reference for Nigerian screening. Each school’s Philippine entrance requirements also form part of admission.'], ['question' => 'When do I begin?', 'answer' => 'Begin several months before the September intake to complete authentication, evaluation and visa processing on schedule.']]],
    ];

    $commonCost = [
        'tuition' => ['title' => 'Tuition', 'kicker' => 'Academic fees', 'body' => 'The school fee schedule and admission offer state the tuition, compulsory charges and payment dates for each academic year.'],
        'hostel' => ['title' => 'Hostel and accommodation', 'kicker' => 'Where you will live', 'body' => 'School-linked housing provides furnished student accommodation close to the academic environment. Room choice determines occupancy and included utilities.'],
        'living' => ['title' => 'Living expenses', 'kicker' => 'Monthly budget', 'body' => 'The student budget covers utilities, mobile data, local transport, books, personal care, healthcare and a contingency reserve.'],
        'food' => ['title' => 'Food', 'kicker' => 'Everyday costs', 'body' => 'Cooking and local meals generally cost less than frequent restaurant or imported-food purchases. Dietary preferences can materially change the monthly budget.'],
        'travel' => ['title' => 'Visa and travel', 'kicker' => 'Getting to the Philippines', 'body' => 'The travel budget covers document authentication, visa processing, insurance, airport transfers and the Lagos–Manila flight.'],
        'summary' => ['title' => 'Budget summary', 'kicker' => 'Build a complete plan', 'items' => ['Confirmed tuition and compulsory school fees', 'Housing deposit and monthly rent', 'Food, transport, utilities and study materials', 'Visa, document and medical costs', 'Flights and arrival allowance', 'Emergency reserve']],
        'comparison' => ['title' => 'Country comparison', 'kicker' => 'Look beyond tuition', 'table' => [['Philippines', 'English-medium environment; tropical climate', 'Moderate'], ['United Kingdom', 'High global visibility; costly living and tuition', 'Very high'], ['Canada', 'Competitive entry; high living costs', 'Very high'], ['Russia', 'Lower-cost options; language and climate considerations', 'Low–moderate'], ['Poland', 'European setting; higher living costs than the Philippines', 'High']]],
        'payment' => ['title' => 'Payment guidance', 'kicker' => 'Pay safely', 'body' => 'Pay through the institution’s official account or a formally documented Medcon channel. Match the beneficiary details to the invoice and retain every receipt.'],
    ];

    $commonPhilippines = [
        'why' => ['title' => 'Why study medicine in the Philippines?', 'kicker' => 'The destination', 'body' => 'English is widely used in higher education and healthcare. The Philippines combines an English-medium medical curriculum, clinical education, a tropical environment and a structured route for international students.'],
        'recognition' => ['title' => 'MDCN approval and licensing', 'kicker' => 'Nigerian pathway', 'body' => 'The profiled medical-school pathways are approved by the Medical and Dental Council of Nigeria. Graduates complete the MDCN registration, assessment and internship requirements in force when they return.'],
        'russia' => ['title' => 'Philippines vs Russia', 'kicker' => 'Compare', 'body' => 'The Philippines offers a predominantly English-speaking environment and tropical climate. Russia can offer lower-cost programs, but language, winter climate and clinical communication deserve close consideration.'],
        'uk' => ['title' => 'Philippines vs United Kingdom', 'kicker' => 'Compare', 'body' => 'UK medical education has strong international visibility but significantly higher tuition and living costs. Entry is also highly competitive.'],
        'canada' => ['title' => 'Philippines vs Canada', 'kicker' => 'Compare', 'body' => 'Canadian medical-school entry requires substantial prior study and offers very limited international places. The Philippines provides a direct international admissions pathway with English-medium medical education.'],
        'ghana' => ['title' => 'Philippines vs Ghana', 'kicker' => 'Compare', 'body' => 'Ghana is geographically closer to Nigeria and offers a familiar West African context. The Philippines provides a different international experience with English-medium instruction and Asian clinical settings.'],
        'poland' => ['title' => 'Philippines vs Poland', 'kicker' => 'Compare', 'body' => 'Poland offers European English-language programs with higher living costs, a colder climate and Polish-language communication during clinical training.'],
        'safety' => ['title' => 'Safety and student wellbeing', 'kicker' => 'Prepare well', 'body' => 'Students follow school guidance, live in approved accommodation, maintain health insurance, keep emergency contacts and observe standard travel precautions.'],
        'career' => ['title' => 'Career planning', 'kicker' => 'Think past graduation', 'body' => 'The graduate pathway covers internship completion, credential verification, licensing examinations, supervised practice and postgraduate training. Medcon guides students on the MDCN route from enrolment.'],
        'colleges' => ['title' => 'Featured colleges', 'kicker' => 'Medcon partners', 'body' => 'Medcon currently profiles PLTCI College of Medicine and The Manila Times College of Subic School of Medicine. Compare the program structure and verified offer details before choosing.'],
    ];

    $tmtcsAdmissions = $commonAdmissions;
    $tmtcsAdmissions['eligibility'] = ['title'=>'Eligibility criteria','kicker'=>'Published MD entry rules','body'=>'Applicants need a completed bachelor’s degree, academic readiness and suitability for medical training. TMTCS also requires a valid NMAT result of at least 40 percentile according to its admissions page.'];
    $tmtcsAdmissions['documents'] = ['title'=>'Documents required','kicker'=>'Published checklist','items'=>['Official Transcript of Records','Certified true copy of NMAT result (at least 40 percentile)','Medical certificate','PSA birth certificate or international equivalent','Certificate of good moral character','Bachelor’s diploma or graduation certificate','Two 2×2 and two 1×1 photographs on white background']];
    unset($commonAdmissions['loans'], $commonAdmissions['scholarships'], $tmtcsAdmissions['loans'], $tmtcsAdmissions['scholarships']);

    $comparisonHeaders = ['Country', 'Typical route', 'Teaching language', 'Clinical language', 'Relative cost', 'Key consideration'];
    $comparisonRows = [
        ['Philippines', 'Pre-med/BS preparation + MD', 'English', 'English and Filipino', 'Moderate', 'English-medium education and tropical setting'],
        ['United Kingdom', 'Direct-entry medicine or graduate entry', 'English', 'English', 'Very high', 'Strong recognition; highly competitive and expensive'],
        ['Canada', 'Bachelor’s degree + MD', 'English/French', 'English/French', 'Very high', 'Very limited international places'],
        ['Russia', 'Direct-entry medical degree', 'English/Russian', 'Russian often needed', 'Low–moderate', 'Language and winter climate require preparation'],
        ['Poland', 'Direct-entry medical degree', 'English', 'Polish during clinics', 'High', 'European setting with higher living costs'],
        ['Ghana', 'Direct-entry medicine', 'English', 'English', 'Moderate–high', 'Closer to Nigeria and a familiar regional setting'],
    ];

    $pltciCost = $commonCost;
    $pltciCost['tuition'] = ['title'=>'Tuition breakdown','kicker'=>'2026/2027 fees','body'=>'Converted from the school’s published INR ranges at INR 96.22 per US$1 and rounded upward to the nearest US$100.', 'headers'=>['Fee component','Per academic year','Five-year total'], 'table'=>[['Tuition','US$3,400–4,000','US$16,700–19,800'],['Examinations and assessment','US$300','US$1,100'],['Total academic cost','US$3,600–4,200','US$17,700–20,800']]];
    $pltciCost['hostel'] = ['title'=>'Hostel and accommodation','kicker'=>'Indian AC hostel','body'=>'The hostel provides furnished air-conditioned rooms, Wi-Fi, security, study areas and proximity to campus.', 'headers'=>['Accommodation','Per year','Five-year total'], 'table'=>[['Indian AC hostel','US$1,100–1,300','US$5,200–6,300']]];
    $pltciCost['living'] = ['title'=>'Living expenses','kicker'=>'Annual budget','body'=>'This budget covers local transport, mobile data, study materials, personal spending and recreation.', 'headers'=>['Category','Annual budget','Notes'], 'table'=>[['Living expenses','US$600–900','Excludes food, hostel and annual travel']]];
    $pltciCost['food'] = ['title'=>'Food','kicker'=>'Indian mess available','body'=>'The Indian mess serves three daily South and North Indian meals with vegetarian and non-vegetarian options.', 'headers'=>['Meal option','Annual fee range','Notes'], 'table'=>[['Indian mess and supplementary dining','US$900–1,100','Three meals daily plus campus dining']]];
    $pltciCost['travel'] = ['title'=>'Visa and travel','kicker'=>'Nigeria to the Philippines','body'=>'The Lagos–Manila travel allowance is US$1,200. The admission package states the visa, authentication, insurance and arrival services included for the student.'];
    $pltciCost['summary'] = ['title'=>'Five-year cost summary','kicker'=>'Complete budget range','body'=>'The complete five-year package is INR 20–25 lakh before conversion.', 'headers'=>['Cost area','USD budget','Basis'], 'table'=>[['Complete five-year total','US$20,800–26,000','Tuition, hostel, food and standard living costs'],['Lagos–Manila travel','US$1,200','Travel allocation']]];
    $pltciCost['comparison'] = ['title'=>'International medical-study comparison','kicker'=>'Compare the complete route','headers'=>$comparisonHeaders,'table'=>$comparisonRows];

    $tmtcsCost = $commonCost;
    $tmtcsCost['tuition'] = ['title'=>'BS–MD fee structure','kicker'=>'Converted to US dollars','body'=>'Converted at PHP 56.289 per US$1 and rounded upward to the nearest US$100. The four-year MD structure and pre-med fee are displayed as distinct stages.', 'headers'=>['Academic stage','Published fee','USD amount'], 'table'=>[['Pre-Med','PHP 550,000','US$9,800'],['MD first year','PHP 280,000','US$5,000'],['MD second year','PHP 280,000','US$5,000'],['MD third year','PHP 240,000','US$4,300'],['MD fourth year','PHP 240,000','US$4,300'],['Additional final semester','PHP 120,000','US$2,200']]];
    $tmtcsCost['hostel'] = ['title'=>'Accommodation and Indian cuisine','kicker'=>'Monthly package','body'=>'Accommodation with breakfast, lunch and dinner costs US$215 per month. The rounded monthly budget is US$300. Excess electricity, premium rooms, books and uniforms are charged separately.'];
    $tmtcsCost['living'] = ['title'=>'Additional fees and living costs','kicker'=>'Costs beyond tuition','headers'=>['Item','Published fee','USD amount'], 'table'=>[['One-time enrolment and admission','PHP 50,000','US$900'],['Documentation, visa, ticket and listed services','PHP 150,000','US$2,700'],['ACR card, visa conversion and extensions','Charged at cost','Shown on the student invoice'],['Books, uniforms and excess electricity','Additional charge','Shown on the student invoice']]];
    $tmtcsCost['food'] = ['title'=>'Food','kicker'=>'Included package','body'=>'Breakfast, lunch and dinner with Indian cuisine are included in the listed US$215 monthly accommodation package. Personal dining and snacks remain separate.'];
    $tmtcsCost['travel'] = ['title'=>'Visa and travel','kicker'=>'Lagos to Manila','body'=>'The Lagos–Manila travel allocation is US$1,200. The PHP 150,000 service package covers documentation, visa, ticket and the listed admission services.'];
    $tmtcsCost['summary'] = ['title'=>'MD cost summary','kicker'=>'Four-year structure','headers'=>['Cost component','USD amount','Notes'], 'table'=>[['Four MD academic years','US$18,600','First through fourth year'],['Additional final semester','US$2,200','Listed separately in the fee structure'],['Pre-Med','US$9,800','Separate from the four-year MD'],['One-time admission','US$900','Published PHP 50,000'],['Accommodation with meals','US$300/month','Rounded monthly budget'],['Travel allocation','US$1,200','Lagos–Manila']]];
    $tmtcsCost['comparison'] = ['title'=>'International medical-study comparison','kicker'=>'Compare the complete route','headers'=>$comparisonHeaders,'table'=>$comparisonRows];

    return [
        'pltci' => [
            'name' => 'PLTCI College of Medicine', 'short' => 'PLTCI', 'location' => 'Solano, Nueva Vizcaya, Philippines', 'established' => '1991', 'duration' => '5-year pathway', 'international' => '300+ Indian students', 'language' => '100% English', 'logo' => 'img/school/pltci-logo.png', 'hero' => 'img/school/pltci-building.jpg',
            'gallery' => ['img/school/pltci-building.jpg','img/school/pltci-library.jpg','img/school/pltci-anatomy.jpg','img/school/pltci-medical.jpg','img/school/pltci-lounge.jpg','img/school/pltci-recreation.jpg'],
            'pages' => [
                'landing' => ['label' => 'Overview', 'title' => 'Begin your medical journey at PLTCI', 'intro' => 'A student-focused Doctor of Medicine pathway in Nueva Vizcaya, with academic foundations, practical learning and Medcon support from application to arrival.', 'sections' => [
                    'proof' => ['title'=>'PLTCI at a glance','kicker'=>'Key facts','stats'=>[['1991','Year established'],['5 years','Medical pathway'],['300+','Indian students'],['100% English','Language of instruction']]],
                    'features' => ['title'=>'A practical route to medicine','kicker'=>'Program strengths','items'=>['Integrated medical learning','Clinical exposure','Faculty mentorship','Community-oriented education']],
                    'why' => ['title'=>'Why PLTCI','kicker'=>'Choose with confidence','body'=>'PLTCI combines a long institutional history with a developing medical program, an English-medium learning environment and a quieter campus setting in Solano.'],
                    'accreditation' => ['title'=>'Accreditation and recognition','kicker'=>'Approved pathway','body'=>'PLTCI is CHED recognised, internationally listed and MDCN approved for the Nigerian pathway. Graduates complete the prevailing MDCN registration and assessment requirements.'],
                    'tour' => ['title'=>'Virtual campus tour','kicker'=>'See the environment','gallery'=>true],
                    'process' => $commonAdmissions['process'],
                    'fees' => ['title'=>'Fees at a glance','kicker'=>'Complete fee range','body'=>'Annual tuition is US$3,400–4,000. The complete five-year fee range is US$20,800–26,000, plus US$1,200 for Lagos–Manila travel. The Cost page contains the full breakdown.'],
                    'life' => ['title'=>'Life at PLTCI','kicker'=>'Beyond the classroom','body'=>'The archived school material highlights library, anatomy, medical, lounge and recreation spaces designed to support focused study and student community.'],
                    'testimonials' => ['title'=>'Student experience','kicker'=>'Campus community','body'=>'PLTCI provides a close-knit student community, academic counselling, faculty mentorship, furnished accommodation, Indian meals and structured support throughout the medical pathway.'],
                    'faqs' => $commonAdmissions['faqs'],
                    'apply' => ['title'=>'Ready to apply?','kicker'=>'Start now','body'=>'Share your academic background with Medcon for an initial eligibility review and a current document checklist.'],
                    'contact' => ['title'=>'Get in touch','kicker'=>'Speak with an adviser','body'=>'Call or WhatsApp +234 703 696 1056, or email info@medconedu.org for school-specific guidance.'],
                ]],
                'about' => ['label'=>'About','title'=>'About PLTCI','intro'=>'Explore the institution’s background, purpose, leadership and external relationships.','sections'=>[
                    'history'=>['title'=>'History and legacy','kicker'=>'Established 1991','body'=>'PLTCI Asia Pacific College of Medicine & Research has developed a student-focused medical learning environment in Nueva Vizcaya, combining academic instruction, laboratories and hospital-based clinical education.'],
                    'mission'=>['title'=>'Mission and vision','kicker'=>'Purpose','body'=>'PLTCI’s mission is to provide quality medical education that builds academic knowledge, clinical skills, ethical values and professional responsibility. Its vision is to be a respected Philippine medical institution producing competent, compassionate and globally ready doctors.'],
                    'leadership'=>['title'=>'Leadership','kicker'=>'Stewardship','body'=>'The Chairman’s message emphasises medical education beyond textbooks, while the Dean’s message highlights theoretical learning combined with practical hospital exposure. Faculty provide classroom, laboratory, research and clinical mentorship.'],
                    'accreditation'=>['title'=>'Accreditation','kicker'=>'Institutional standing','body'=>'PLTCI is CHED recognised, internationally listed through medical education registries and MDCN approved for Nigerian applicants.'],
                    'partnerships'=>['title'=>'Collaborations and partnerships','kicker'=>'Connected learning','body'=>'Academic and clinical collaboration centres on PLTCI Medical Center, patient-care exposure, medical research, student learning and exchange, healthcare education and international medical-education relationships.']]],
                'academics' => ['label'=>'Academics','title'=>'Doctor of Medicine academics','intro'=>'A structured view of the academic and clinical journey described by PLTCI.','sections'=>[
                    'md'=>['title'=>'Medical program','kicker'=>'Five-year pathway','body'=>'The five-year sequence covers pre-clinical foundations, para-clinical sciences, clinical introduction, advanced clinical training and a final clinical internship. Teaching is delivered in English.'],
                    'premed'=>['title'=>'Pre-Med','kicker'=>'Entry preparation','body'=>'Pre-Med builds the biology, chemistry, anatomy, psychology, communication and healthcare-science foundation required for progression into advanced medical study.'],
                    'curriculum'=>['title'=>'Curriculum','kicker'=>'Progressive learning','items'=>['Foundational biomedical sciences','Pathology and disease mechanisms','Clinical diagnosis and management','Professionalism, ethics and communication','Community and population health']],
                    'clinical'=>['title'=>'Clinical training','kicker'=>'From Year 1','body'=>'Training at PLTCI Medical Center includes OPD observation, ward rounds, structured patient interaction, faculty-led case discussions, clinical demonstrations and multidisciplinary teamwork.'],
                    'rotations'=>['title'=>'Hospital rotations','kicker'=>'PLTCI Medical Center','items'=>['Internal Medicine','Surgery','Paediatrics','Obstetrics and Gynaecology','Emergency Medicine','Community Health','General Ward','Psychiatry']],
                    'labs'=>['title'=>'Simulation and skills labs','kicker'=>'Practise safely','body'=>'Simulation facilities allow students to practise clinical procedures, patient assessment and communication in a controlled setting before direct patient care. Anatomy and practical laboratory learning are also included.'],
                    'research'=>['title'=>'Research','kicker'=>'Evidence in practice','body'=>'Students are introduced to research literacy, scientific inquiry and the use of evidence in clinical decision-making.'],
                    'calendar'=>['title'=>'Academic calendar','kicker'=>'September intake','body'=>'The 2026/2027 academic session begins in September 2026. The registrar issues the full term, holiday, examination and clinical-block calendar to enrolled students.'],
                    'exams'=>['title'=>'Examinations','kicker'=>'Assessment','body'=>'Assessment combines written examinations, laboratory practicals, clinical case work and competency evaluation throughout the program.'],
                    'emergency'=>['title'=>'Emergency medicine','kicker'=>'Respond with confidence','body'=>'Emergency learning introduces systematic assessment, stabilisation principles, teamwork and referral within supervised training.']]],
                'admissions' => ['label'=>'Admissions','title'=>'PLTCI admissions','intro'=>'Understand the application, document and immigration journey before you commit.','sections'=>$commonAdmissions],
                'cost' => ['label'=>'Cost','title'=>'Planning the cost of PLTCI','intro'=>'A detailed tuition and living-cost framework converted to US dollars for the September 2026 intake.','sections'=>$pltciCost],
                'philippines' => ['label'=>'MBBS Philippines','title'=>'Studying medicine in the Philippines','intro'=>'A decision guide for PLTCI applicants comparing destination, recognition and career considerations.','sections'=>$commonPhilippines],
            ]
        ],
        'tmtcs' => [
            'name' => 'The Manila Times College of Subic School of Medicine', 'short' => 'TMTCS School of Medicine', 'location' => 'Subic Bay Freeport Zone, Zambales, Philippines', 'established' => '2021', 'duration' => '4-year MD', 'international' => 'International admissions', 'language' => 'English medium', 'logo' => 'img/school/tmtcs-medicine-logo.png', 'hero' => 'img/school/tmtcs-campus.webp',
            'gallery' => ['img/school/tmtcs-campus.webp','img/school/tmtcs-med-students.webp','img/school/tmtcs-medical-training.jpg','img/school/tmtcs-community.webp','img/school/tmtcs-outreach.webp','img/school/tmtcs-bghmc.webp'],
            'pages' => [
                'landing' => ['label'=>'Overview','title'=>'Study Doctor of Medicine in Subic','intro'=>'An outcomes-based Doctor of Medicine program developing clinically capable, ethical and community-responsive physicians in an English-medium environment.','sections'=>[
                    'proof'=>['title'=>'School of Medicine at a glance','kicker'=>'Key facts','stats'=>[['2021','MD permit granted'],['4 years','Doctor of Medicine'],['Subic','Campus location'],['English','Learning environment']]],
                    'features'=>['title'=>'Built for future physicians','kicker'=>'Program strengths','items'=>['Outcomes-based curriculum','Case and problem-based learning','Community engagement','Partner-hospital exposure']],
                    'why'=>['title'=>'Why TMTCS School of Medicine','kicker'=>'A supportive setting','body'=>'TMTCS emphasizes medical knowledge, clinical competence, ethics, communication and social accountability within the accessible Subic Bay Freeport Zone.'],
                    'accreditation'=>['title'=>'Accreditation and recognition','kicker'=>'Approved pathway','body'=>'The School of Medicine received authority to offer the MD program in August 2021, is listed in the World Directory of Medical Schools and is MDCN approved. Graduates complete the prevailing registration requirements.'],
                    'tour'=>['title'=>'Virtual campus tour','kicker'=>'Explore Subic','gallery'=>true],
                    'process'=>$commonAdmissions['process'],
                    'fees'=>['title'=>'Fees at a glance','kicker'=>'Four-year MD','body'=>'Tuition is US$5,000 for each of Years 1 and 2, then US$4,300 for each of Years 3 and 4. Pre-Med costs US$9,800. The Cost page lists every additional charge and inclusion.'],
                    'life'=>['title'=>'Life at TMTCS','kicker'=>'Campus and community','body'=>'Students study in Subic and participate in community-oriented learning, peer collaboration and supervised clinical experiences across partner settings.'],
                    'testimonials'=>['title'=>'Student experience','kicker'=>'Learning culture','body'=>'TMTCS provides a nurturing, student-centred environment built around peer learning, faculty mentoring, community engagement and supervised clinical education.'],
                    'faqs'=>$commonAdmissions['faqs'],
                    'apply'=>['title'=>'Ready to apply?','kicker'=>'Start your review','body'=>'Send Medcon your qualification details for a Doctor of Medicine eligibility assessment and current admissions checklist.'],
                    'contact'=>['title'=>'Get in touch','kicker'=>'Official support','body'=>'Medcon: +234 703 696 1056. TMTCS admissions: admissions@tmtc.edu.ph, +63 927 365 8270 or +63 945 650 6484.']]],
                'about' => ['label'=>'About','title'=>'About TMTCS School of Medicine','intro'=>'The history, mission, leadership and clinical relationships behind the Doctor of Medicine program.','sections'=>[
                    'history'=>['title'=>'History','kicker'=>'A health-sciences foundation','body'=>'TMTCS expanded from nursing and medical laboratory science into other health programs before receiving a permit to offer Doctor of Medicine beginning in August 2021.'],
                    'mission'=>['title'=>'Mission and vision','kicker'=>'Competence with conscience','body'=>'The School aims to develop competent, ethical and socially responsive physicians through outcomes-based education, multidisciplinary collaboration, mentoring and patient-centred care, while becoming a centre of innovation and social accountability.'],
                    'leadership'=>['title'=>'Leadership','kicker'=>'School guidance','body'=>'Dr Rosalinda Elena B. Milla serves as Founding Dean, Dr Corazon Valdez serves as Dean and Monica Ang, PhD serves as President of The Manila Times College of Subic.'],
                    'accreditation'=>['title'=>'Accreditation','kicker'=>'Program status','body'=>'The Doctor of Medicine program holds its 2021 operating authority, is listed in the World Directory of Medical Schools and carries MDCN approval for Nigerian students.'],
                    'partnerships'=>['title'=>'Affiliations and partner hospitals','kicker'=>'Clinical collaboration','items'=>['Bataan General Hospital and Medical Center','James L. Gordon Memorial Hospital','Jose B. Lingad Memorial General Hospital','President Ramon Magsaysay Memorial Hospital']]]],
                'academics' => ['label'=>'Academics','title'=>'Doctor of Medicine academics','intro'=>'The supplied TMTCS structure covers only the four-year Doctor of Medicine program.','sections'=>[
                    'md'=>['title'=>'Doctor of Medicine program','kicker'=>'Four-year pathway','body'=>'An integrated, outcomes-based program designed to develop medical knowledge, clinical skills, professional values and lifelong learning.'],
                    'premed'=>['title'=>'Pre-Med preparation','kicker'=>'Before the MD','body'=>'Pre-Med delivers the science preparation required before the four-year MD. The school evaluates the applicant’s previous qualifications and assigns the correct entry stage.'],
                    'curriculum'=>['title'=>'Curriculum','kicker'=>'Integrated sciences','items'=>['Foundation Sciences: normal structure, function and health','Clinical Sciences: disease, diagnosis and management','Integrative Sciences: clinical and community application','Year 4 apprenticeship in clinical and community settings']],
                    'clinical'=>['title'=>'Clinical training','kicker'=>'Real-world learning','body'=>'Students apply knowledge in supervised clinical and community settings while developing reasoning, teamwork, ethics and patient-centred communication.'],
                    'rotations'=>['title'=>'Rotations and partner hospitals','kicker'=>'Across care settings','body'=>'Clinical rotations take place through Bataan General Hospital and Medical Center, James L. Gordon Memorial Hospital, Jose B. Lingad Memorial General Hospital and President Ramon Magsaysay Memorial Hospital.'],
                    'labs'=>['title'=>'Simulation and skills labs','kicker'=>'Competency development','body'=>'The curriculum refers to hands-on skills development, but the supplied Doctor of Medicine pages do not provide a detailed inventory of simulation facilities.'],
                    'research'=>['title'=>'Research','kicker'=>'Evidence and inquiry','body'=>'Research and innovation are integrated into the program’s stated outcomes, supporting critical appraisal and health-system improvement.'],
                    'calendar'=>['title'=>'Academic calendar','kicker'=>'September intake','body'=>'The 2026/2027 academic session begins in September 2026. The registrar issues the term, holiday, examination and clinical-rotation schedule to enrolled students.'],
                    'exams'=>['title'=>'Examinations','kicker'=>'Outcomes-based assessment','body'=>'Assessment measures medical knowledge, clinical skills, communication, professionalism and community-health competence across the four-year MD.'],
                    'emergency'=>['title'=>'Emergency medicine','kicker'=>'Clinical readiness','body'=>'Emergency-care training develops rapid assessment, stabilisation, clinical teamwork, referral and patient communication through clinical sciences and hospital rotations.']]],
                'admissions' => ['label'=>'Admissions','title'=>'TMTCS Doctor of Medicine admissions','intro'=>'The published school requirements combined with practical guidance for Nigerian applicants.','sections'=>$tmtcsAdmissions],
                'cost' => ['label'=>'Cost','title'=>'Planning the cost of TMTCS MD','intro'=>'The supplied fee structure converted to rounded US-dollar planning figures, with pre-med separated from the four-year MD.','sections'=>$tmtcsCost],
                'philippines' => ['label'=>'MBBS Philippines','title'=>'Studying medicine in the Philippines','intro'=>'A destination and licensing guide for prospective TMTCS Doctor of Medicine students.','sections'=>$commonPhilippines],
            ]
        ]
    ];
}
